# Cloudflare Pages configuration for Next.js
# https://developers.cloudflare.com/pages/platform/functions/

[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NEXT_USE_TRAILING_SLASH = "true"
  NEXT_OUTPUT_EXPORT = "true"

# Handle Next.js routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/bg/*"
  to = "/bg/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/en/*"
  to = "/en/index.html"
  status = 200
  force = false

# Enable SPA mode for client-side routing
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true 