name: Supabase Keep-Alive

on:
  # Run every 6 hours
  schedule:
    - cron: '0 */6 * * *'
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  ping-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug Environment
        run: |
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "Working directory: $(pwd)"
          echo "Contents of .github/workflows:"
          ls -la .github/workflows
          echo "Secrets exist check (true/false):"
          echo "NEXT_PUBLIC_SUPABASE_URL exists: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL != '' }}"
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY exists: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY != '' }}"

      - name: Simple Health Check
        run: |
          echo "Attempting a simple curl to verify Supabase is reachable"
          # This should work even without authentication
          SUPABASE_URL="${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}"
          if [ -z "$SUPABASE_URL" ]; then
            echo "⚠️ NEXT_PUBLIC_SUPABASE_URL is not set!"
            exit 1
          else
            echo "Using Supabase URL: ${SUPABASE_URL}"
            # Test if the URL is reachable
            curl -s -o /dev/null -w "Status code: %{http_code}\n" "$SUPABASE_URL"
            echo "Ping completed at $(date)"
          fi 